### PR TITLE
Get priority lakes

### PR DESCRIPTION
**Pull request by limnoliver**
Wrote a quick function to get priority lakes from available temperature data. Eventually, you could rename `priority_lakes` to `site_ids` when you're ready to go beyond testing. `create_format_task_plan` can point to the temp observations downloaded to `in/all_temp_data.feather` to write individual lake observed temperature files. 

For `priority_lakes_by_choice` I pointed to the same test file, assuming this could be used to update the list of lakes we know we want to include (or can just point to new file). 

For `priority_lakes_by_data`, I tried to cover a few data spaces to select upon. First, a lake must meet a minimum n value (all observations, so each unique lake-date-depth counts) criteria, then lakes can be a priority lake if they meet any of the other criteria. For these criteria, I was thinking a lake could be considered priority if it had good coverage through time (`n_years`), consistent coverage through time (`n_years_with_10days`), good intra-annual coverage (`n_years_with_7months`), or just a crap ton of days of observation (`n_days`). Then the function exports the unique lakes that qualify for each of these criteria. At the current cutoffs, `priority_lakes_by_data` is 60 lakes.  These are all arbitrary of course, but hopefully this gives us the structure to play around a bit with how we select priority lakes. 

Are lake names important in this step? We could add a crosswalk for those.

### CODE REVIEW

**Comment by wdwatkins** [comment]
I think we will want lake names, so they can be used in results summaries at the end.

**Comment by aappling-usgs** [comment]
@wdwatkins are you suggesting a file other than 1_format.yml for the remake recipes that @limnoliver added? If so, I don't feel strongly about that part - yes, it will require a manual step to force the rebuild, but whether that occurs in 1_format.yml or in 0_prioritize.yml doesn't strike me as strongly related to whether it's manually or automatically triggered.

Note discussion at https://github.com/USGS-R/lake-temperature-process-models/pull/2#discussion_r218238478 and readme at https://github.com/USGS-R/lake-temperature-model-prep/pull/23 with ideas/support for facilitating the manual transfers among pipelines.

**Comment by wdwatkins** [comment]
Ah ok, I hadn't seen the discussion of using an indicator file copied from the other pipeline.  Yes, if it is going to be a remake step then I agree it doesn't matter if it is in a different file.

**Comment by wdwatkins** [comment]
@limnoliver should I go ahead and merge, or do you want to add the lake names first?

**Comment by limnoliver** [comment]
@wdwatkins I'll add lake names today.

**Comment by limnoliver** [comment]
Ok @wdwatkins -- added the lake names using a crosswalk, but also changed the way the dependencies from pipeline #1 were handled per conversation with @jzwart. Jake, can you take a quick look at `1_format.yml` to make sure that is consistent with your convention? Also adding those dependencies to `lake-temperature-model-prep` now...

**Comment by wdwatkins** [comment]
Looks good.  @jzwart can you merge if you are happy?

**Comment by jzwart** [comment]
looks good!

**Pull request merged**
